### ISSUE TITLE
Hexo添加评论系统Valine | Benjamin Zhou's Blog

### ISSUE THREAD

**Issue by KayChou** [KayChou/KayChou.github.io#2]
https://benjaminkai.github.io/2018/08/11/Hexo%E6%B7%BB%E5%8A%A0%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9FValine/#more 

 一款简洁，方便，好用的评论系统。

**Comment by benjaminkai** [comment]
测试我的gitalk
